// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCatiCSriZ8kf1YImvEnzawUxaAk38Mzbw',
    appId: '1:504247630694:android:9b3e1af266b8a8ab1126a7',
    messagingSenderId: '504247630694',
    projectId: 'smart-daigaku',
    storageBucket: 'smart-daigaku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXG6P5Mx41uaOmHGjfpMoElraRCgIgTYE',
    appId: '1:504247630694:ios:680e0297386c47d51126a7',
    messagingSenderId: '504247630694',
    projectId: 'smart-daigaku',
    storageBucket: 'smart-daigaku.appspot.com',
    androidClientId: '504247630694-7q2v4vuqp645vjtd24jahpm7lt8j7tuj.apps.googleusercontent.com',
    iosClientId: '504247630694-7eh7jueefc0sm2gidsj8cqpro4temedh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartdaigaku',
  );
}
